apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
        - name: reddit-app
          image: mshow1980/tuesday_app:1.5-11
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: reddit-app-service
  labels:
    app: rreddit-app 
spec:
  selector:
    app: reddit-app

  ports:
    - port: 3000
      targetPort: 3000

  type: NodePort
